require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
-- trying out lsp
require "user.lsp"
-- 
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.lualine"
-- require "user.whichkey"
require "user.neorg"
require "user.orgmode"
